In [1]:
import pandas as pd
import sqlite3

In [2]:
orders = pd.read_csv("C:/Users/Shahin Banu/Downloads/orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [3]:
users = pd.read_json("C:/Users/Shahin Banu/Downloads/users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [4]:
conn = sqlite3.connect("restaurants.db")

# Run SQL file once to create table
with open("C:/Users/Shahin Banu/Downloads/restaurants.sql", "r") as f:
    sql_script = f.read()

conn.executescript(sql_script)

restaurants = pd.read_sql("SELECT * FROM restaurants", conn)

restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [5]:
orders_users = orders.merge(
    users,
    on="user_id",
    how="left"
)

In [6]:
final_dataset = orders_users.merge(
    restaurants,
    on="restaurant_id",
    how="left"
)

In [7]:
final_dataset.to_csv(
    "final_food_delivery_dataset.csv",
    index=False
)